### PR TITLE
Add additional field options for indexing

### PR DESCRIPTION
**Pull request by janette**
This branch should work with https://github.com/GetDKAN/data-catalog-frontend/pull/16
Related ticket: https://github.com/getdkan/dkan2/issues/344

## QA Steps
1. Confirm you can add additional schema fields like publisher.name and distribution.title to the search index `/admin/config/search/search-api/index/dkan/fields`

### CODE REVIEW

**Comment by dafeder** [comment]
Found an issue - tried to add `accessLevel` and got this error:

image

**Comment by janette** [comment]
@dafeder if you change the machine name to be all lower case it will work

**Comment by dafeder** [comment]
OK - I think we should make another ticket to make that happen automatically.

Last question - why the changes to the schema?

**Comment by janette** [comment]
the getProperty functions don't follow the `$ref`, they just quit there and return nothing.

**Pull request merged**
